version: '2.23'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=Etc/UTC
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports: 
      - "8000:8000"
      - "9443:9443"
      - "9002:9000"
    volumes:  
      - ./volumes/portainer-ce/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    

